In [21]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sn
from sklearn.datasets import load_iris
var = load_iris()

In [22]:
dir(var)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [23]:
from sklearn.model_selection import KFold
kf = KFold(n_splits= 5)
kf

KFold(n_splits=5, random_state=None, shuffle=False)

In [34]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [93]:
from sklearn.linear_model import LogisticRegression
model1 = LogisticRegression()
from sklearn.svm import SVC
model2 = SVC()
from sklearn.ensemble import RandomForestClassifier
model3 = RandomForestClassifier()
for x,y in kf.split(var.data,var.target):
    X_train, X_test, y_train, y_test = var.data[x], var.data[y],var.target[x], var.target[y]
    model1.fit(X_train,y_train)
    print(model1.score(X_test,y_test))
    model2.fit(X_train,y_train)
    print(model2.score(X_test,y_test))
    model3.fit(X_train,y_train)
    print(model3.score(X_test,y_test))

C:\Users\jhapr\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.98
0.96
0.98
0.96
0.98
0.94
0.98
0.94
0.98


In [91]:
from sklearn.model_selection import StratifiedKFold
kf = StratifiedKFold(n_splits= 3)
kf
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
for x,y in kf.split(var.data,var.target):
    X_train, X_test, y_train, y_test = var.data[x], var.data[y],var.target[x], var.target[y]
    model1.fit(X_train,y_train)
    print(model1.score(X_test,y_test))
    model2.fit(X_train,y_train)
    print(model2.score(X_test,y_test))
    model3.fit(X_train,y_train)
    print(model3.score(X_test,y_test))

C:\Users\jhapr\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.98
0.96
0.98
0.96
0.98
0.94
0.98
0.94
0.96


In [92]:
from sklearn.model_selection import cross_val_score
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'),var.data, var.target,cv=5)

array([1.        , 0.96666667, 0.93333333, 0.9       , 1.        ])

In [55]:
cross_val_score(SVC(gamma='auto'),var.data, var.target,cv=5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [56]:
cross_val_score(RandomForestClassifier(n_estimators=40),var.data, var.target,cv=5)

array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 1.        ])

In [67]:
cross_val_score(RandomForestClassifier(n_estimators=10),var.data, var.target,cv=5)

array([0.96666667, 0.96666667, 0.93333333, 0.93333333, 1.        ])